language: node_js

node_js:
  - "lts/*"

install:
  - npm install
  - npm run build

after_script:
  - zip -r release.zip dist

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: release.zip
  skip_cleanup: true
  on:
    tags: true
