language: node_js

node_js:
  - "lts/*"

install:
  - echo Building Plumber $TRAVIS_TAG-$TRAVIS_BUILD_NUMBER
  - npm install
  - npm run build
  - cp install/iis/web.config dist/
  - cd dist
  - touch version.txt
  - echo $TRAVIS_TAG-$TRAVIS_BUILD_NUMBER > version.txt
  - zip -r ../plumber-sc.$TRAVIS_TAG.zip .
  - cd ..

script: npm run test

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: plumber-sc.$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    tags: true
