language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "lts/*"

install:
  - npm install
  - npm run build
  - cp install/iis/web.config dist/
  - cd dist
  - zip -r ../release.zip .

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: release.zip
  skip_cleanup: true
  on:
    tags: true
