language: node_js

node_js:
  - "lts/*"

install:
  - npm install
  - npm run build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  skip_cleanup: true
  on:
    tags: true
